version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://dev_username:dev_password@db/analitics

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "dev_username"
      POSTGRES_PASSWORD: "dev_password"
      POSTGRES_DB: "analitics"
    ports:
      - "5432:5432"
